services:
  postgres:
    image: postgres:15-alpine
    container_name: barea_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: barea_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    container_name: barea_adminer
    restart: always
    ports:
      - "8081:8080"

volumes:
  postgres_data: